analyzer:
  errors:
    todo: ignore
  exclude:
    - "**/*.g.dart"

linter:
  rules:
    - always_declare_return_types
    - always_specify_types
    - cancel_subscriptions
    - close_sinks
    - comment_documentation
    - diagnostic_describe_utils
    - empty_statements
    - exhaustive_cases
    - file_names
    - hash_and_equals
    - implementation_imports
    - iterable_contains_unrelated_type
    - literal_only_in_collection_types
    - missing_final_in_for_each
    - no_adjacent_strings
    - no_duplicate_case_values
    - no_leading_underscores_for_library_prefixes
    - no_logic_in_create_state
    - no_runtimeType_toString
    - no_self_assignment_in_operator
    - no_silent_typo
    - no_use_unsafe_html
    - null_aware_before_operator
    - omit_local_variable_types
    - one_member_abstracts
    - only_throw_errors
    - prefer_adjacent_string_concatenation
    - prefer_asserts_in_initializer_lists
    - prefer_final_fields
    - prefer_final_in_for_each
    - prefer_final_locals
    - prefer_interpolation_to_compose_strings
    - prefer_null_aware_method_calls
    - prefer_single_quotes
    - prefer_typing_uninitialized_variables
    - public_member_api_docs
    - recursive_getters
    - sort_child_properties_last
    - sort_named_parameter_values
    - sort_pub_dependencies
    - test_group_import
    - throw_in_catch_block_with_non_exception
    - type_annotate_public_apis
    - unnecessary_lambdas
    - unnecessary_parenthesis
    - unnecessary_this
    - use_build_context_synchronously
    - use_enums
    - use_extension_type_syntax
    - use_late_for_private_fields_and_methods
    - use_named_routes
    - use_raw_strings
    - use_reified_generic_syntax
    - void_checks