include: package:flutter_lints/rules.yaml

linter:
  rules:
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    always_specify_types: false
    avoid_print: true